[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
gas_reports = ["*"]
test = 'test/'
cache_path = 'forge-cache'
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/"
]